### ISSUE TITLE
scala/collection/GenTraversableOnce$class error on run

### ISSUE THREAD

**Issue by jsolack** [kogecoo/dl4j-examples-scala#1]
I am getting an error when running based on your build.sbt

if i run change scala version to 2.10.4 it works

**Comment by kogecoo** [comment]
Thank you for your reporting.

It might be a same problem with following article. I'll also fix by the same way.
http://stackoverflow.com/questions/26351338/running-spark-scala-example-fails

**Comment by kogecoo** [comment]
fixed at dace763f7e58161de883db95460d307ea623ac4b
